# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 11:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 13, 11, 44, 2, 233042, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
