# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_works_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
