# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-20 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_buyer_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
