# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-23 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0006_auto_20160722_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=32, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='密码')),
                ('is_active', models.IntegerField(blank=True, verbose_name='is_active')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
                ('mail', models.EmailField(max_length=50, verbose_name='邮箱')),
            ],
            options={
                'db_table': 'myuser',
            },
        ),
    ]
