# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-23 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0008_auto_20160723_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='artist_name',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='艺术家姓名'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_artist',
            field=models.BooleanField(default=False, verbose_name='是否是艺术家'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='帐号是否可用'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户名'),
        ),
    ]
